import { useEffect, useState } from "react";
import WordBox from "./wordBox";
import Word from "./Word";

const LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
const DICTIONARY = [
  "TOGETHER", "HELLO", "NO", "NOR", "OR", "WORLD", "REACT", "CODE",
  "FRIEND", "LOVE", "HAPPY", "SAD", "JUMP", "RUN",
  "FAST", "SLOW", "LIGHT", "DARK", "SUN", "MOON",
  "STAR", "SKY", "EARTH", "WATER", "FIRE", "AIR",
  "TREE", "FLOWER", "MUSIC", "DANCE", "SMILE", "LAUGH",
  "BOOK", "LEARN", "TEACH", "PLAY", "GAME", "FUN",
  "HOME", "HOUSE", "FAMILY", "PEACE", "HOPE", "DREAM",
  "DEBUG", "SCRIPT", "ARRAY", "OBJECT", "FUNCTION",
  "VARIABLE", "CONSTANT", "LOOP", "IF", "ELSE", "SWITCH",
  "BUTTON", "INPUT", "FORM", "PAGE", "SECTION", "HEADER",
  "SUCCESS", "FAILURE", "POWER", "STRENGTH", "BRAVE", "KIND",
  "ALWAYS", "NEVER", "SOMETIMES", "MAYBE", "AGAIN", "LATER",
  "SYSTEM", "NETWORK", "SERVER", "DATABASE", "LOGIC", "ERROR",
  "CLASS", "IMPORT", "EXPORT", "RETURN", "PROMISE", "AWAIT",
  "TIME", "DATE", "YEAR", "MONTH", "WEEK", "DAY",
  "CITY", "ROAD", "LIFE", "MIND", "SOUL", "BODY",
  "WINDOW", "SCREEN", "KEYBOARD", "MOUSE", "PHONE", "LAPTOP",
  "COFFEE", "FOOD", "SLEEP", "WORK", "STUDY", "REST",
  "CREATE", "UPDATE", "DELETE", "REMOVE", "START", "FINISH",
  "ANIMAL", "BIRD", "FISH", "RAIN", "SNOW", "WIND", "MOUNTAIN", 
  "RIVER", "OCEAN", "FOREST", "GREEN", "BLUE", "RED", "WHITE", 
  "BLACK", "YELLOW", "ORANGE", "PURPLE", "GOLD", "SILVER", 
  "BRAIN", "HEART", "HEALTH", "STRONG", "SMART", "HONEST", 
  "ANGRY", "CALM", "PROUD", "AFRAID", "SILENT", "LOUD", 
  "FRIENDLY", "GENTLE", "SIMPLE", "MODERN", "VIRTUAL", "DIGITAL", 
  "MEMORY", "STORAGE", "CACHE", "BROWSER", "LINK", "URL", 
  "IMAGE", "VIDEO", "AUDIO", "TEXT", "FONT", "STYLE", 
  "DESIGN", "MODEL", "VIEW", "CONTROLLER", "API", "JSON", 
  "CLIENT", "SOCKET", "REQUEST", "RESPONSE", "HEADER", "FOOTER", 
  "SIDEBAR", "MODAL", "POPUP", "ALERT", "MESSAGE", "EMAIL", 
  "LOGIN", "SIGNUP", "USER", "ADMIN", "PASSWORD", "TOKEN", 
  "SEARCH", "FILTER", "SORT", "LOAD", "SAVE", "CANCEL", 
  "BREAD", "FRUIT", "TEA", "MILK", "EAT", "DRINK", 
  "SCHOOL", "COLLEGE", "OFFICE", "STREET", "SPACE", "GALAXY",

  // --- আরও নতুন শব্দ (Batch 3) ---
  "ALGORITHM", "ASYNC", "BACKEND", "FRONTEND", "FRAMEWORK", "LIBRARY",
  "PRODUCTION", "DEVELOPMENT", "VERSION", "COMMIT", "PUSH", "PULL",
  "BRANCH", "MERGE", "CLONE", "DEPLOY", "HOSTING", "DOMAIN",
  "AUTHENTICATION", "AUTHORIZATION", "SECURITY", "ENCRYPT", "DECRYPT",
  "SHARP", "BLUNT", "HEAVY", "THIN", "THICK", "WIDE", "NARROW",
  "CLEAN", "DIRTY", "FRESH", "STALE", "HOT", "COLD", "WARM",
  "BETTER", "BEST", "GOOD", "BAD", "WORST", "GREAT", "AWESOME",
  "BEAUTIFUL", "UGLY", "RICH", "POOR", "YOUNG", "OLD", "NEW",
  "HISTORY", "FUTURE", "PRESENT", "MORNING", "AFTERNOON", "EVENING", "NIGHT",
  "SUMMER", "WINTER", "SPRING", "AUTUMN", "WEATHER", "STORM", "THUNDER",
  "BICYCLE", "CAR", "TRAIN", "PLANE", "SHIP", "ROCKET", "BRIDGE",
  "ENERGY", "LIGHTNING", "PLANET", "UNIVERSE", "ATOM", "SCIENCE",
  "DOCTOR", "ENGINEER", "ARTIST", "PLAYER", "LEADER", "HERO",
  "VOICE", "SOUND", "SIGHT", "TOUCH", "SMELL", "TASTE",
  "TRUE", "FALSE", "NULL", "UNDEFINED", "NaN", "BOOLEAN", "STRING", "NUMBER",
  "MAP", "SET", "STACK", "QUEUE", "TREE", "GRAPH", "NODE",
  "BOTTLE", "CHAIR", "TABLE", "BED", "DOOR", "WALL", "FLOOR", "ROOF",
  "GARDEN", "PARK", "ISLAND", "DESERT", "VALLEY", "HILL", "STONE",
  "WATCH", "CLOCK", "MONEY", "WALLET", "BAG", "CLOTHES", "SHIRT", "ACADEMY", "ACCOUNT", "ACTION", "ACTIVE", "ADDRESS", "ADVICE", "ALBUM", 
  "ALIVE", "AMOUNT", "ANSWER", "APPLE", "AREA", "ARMOR", "ARROW", 
  "ATTACK", "AUTHOR", "BALANCE", "BALLOON", "BAMBOO", "BANK", "BATTERY", 
  "BEACH", "BEAST", "BEAUTY", "BELIEVE", "BEYOND", "BLOCK", "BLOOD", 
  "BONE", "BORDER", "BOTTOM", "BRAIN", "BRANCH", "BREEZE", "BRIGHT", 
  "BUILD", "BULLET", "BURST", "BUTTON", "CAMERA", "CAMPUS", "CANDLE", 
  "CANVAS", "CAPTAIN", "CASTLE", "CAVE", "CENTER", "CHANCE", "CHANGE", 
  "CHANNEL", "CHARGE", "CHART", "CHECK", "CHESS", "CHIEF", "CHILD", 
  "CHOICE", "CIRCLE", "CLASSIC", "CLICK", "CLIMB", "CLOUD", "COAST", 
  "COLLECT", "COLOR", "COLUMN", "COMBAT", "COMFORT", "COMMON", "COMPASS", 
  "COMPLEX", "CONFIG", "CONNECT", "CONTENT", "CONTEXT", "COOK", "COOL", 
  "COPPER", "CORNER", "COSMOS", "COUNT", "COUNTRY", "COUPLE", "COURSE", 
  "COVER", "CRAFT", "CRASH", "CREDIT", "CRITICAL", "CROWN", "CRYSTAL", 
  "CULTURE", "CURRENT", "CURSOR", "CUSTOM", "CYCLE", "DANGER", "DATA", 
  "DEAD", "DEBATE", "DECIDE", "DEEP", "DEFAULT", "DEGREE", "DELAY", 
  "DELTA", "DEMO", "DEPEND", "DEPTH", "DESERVE", "DEVICE", "DIALOG", 
  "DIAMOND", "DIARY", "DIRECT", "DISCO", "DISPLAY", "DISTANCE", "DIVIDE", 
  "DOUBLE", "DOUBT", "DRAGON", "DRAWER", "DREAMER", "DRIVER", "DRONE", 
  "DROP", "DUST", "DYNAMIC", "EAGLE", "EARLY", "ECHO", "EDITOR", 
  "EFFECT", "EFFORT", "EGG", "ELECTRIC", "ELEMENT", "ELITE", "EMPTY", 
  "ENGINE", "ENOUGH", "ENTER", "ENTITY", "ENTRY", "EQUAL", "EQUIP", 
  "ESCAPE", "EVENT", "EXACT", "EXOTIC", "EXPECT", "EXPERT", "EXPLORE", 
  "EXTEND", "EXTRA", "EYE", "FABRIC", "FACTOR", "FAIR", "FAITH", 
  "FALSE", "FAMOUS", "FANTASY", "FARM", "FASHION", "FATAL", "FAVORITE", 
  "FEAR", "FEATHER", "FEATURE", "FEED", "FEEL", "FEMALE", "FIELD", 
  "FIGHT", "FILE", "FINAL", "FIND", "FINGER", "FIREWALL", "FLAME", 
  "FLASH", "FLAVOR", "FLIGHT", "FLOOD", "FOCUS", "FORCE", "FORGET", 
  "FORMAT", "FORWARD", "FRAME", "FREEZE", "FRIENDLY", "FROST", "FUEL", 
  "FUTURE", "GALLERY", "GARAGE", "GATE", "GEAR", "GENIUS", "GHOST", 
  "GIANT", "GIFT", "GLASS", "GLOBAL", "GLORY", "GLOVE", "GLOW", 
  "GOAL", "GRACE", "GRADE", "GRAIN", "GRAND", "GRAPHS", "GRASS", 
  "GRAVE", "GRID", "GROUP", "GUARD", "GUIDE", "GUITAR", "GUM", 
  "HABIT", "HAMMER", "HAND", "HANDLE", "HARBOR", "HARD", "HARVEST", "HIDDEN", "HISTORY", "HOLLOW", "HONOR", "HORIZON", "HORROR", "HOSPITAL", 
  "HUMAN", "HUNTER", "HYBRID", "ICON", "IDEA", "IDENTITY", "IGNORE", 
  "ILLUSION", "IMPACT", "IMPROVE", "INDEX", "INFINITY", "INFO", "INHERIT", 
  "INJURY", "INNER", "INNOCENT", "INSIDE", "INSTALL", "INSTANT", "INTENT", 
  "INVITE", "IRON", "ISLAND", "JACKET", "JOURNEY", "JUDGE", "JUICE", 
  "JUNGLE", "JUNIOR", "JUSTICE", "KERNEL", "KICK", "KILLER", "KINGDOM", 
  "KITCHEN", "KNIGHT", "KNIFE", "KNOCK", "KNOWLEDGE", "LABEL", "LABOR", 
  "LADDER", "LAND", "LANDSCAPE", "LANGUAGE", "LANTERN", "LASER", "LAUNCH", 
  "LAYER", "LAYOUT", "LEADER", "LEGEND", "LEMON", "LENGTH", "LESSON", 
  "LETTER", "LEVEL", "LIBRARY", "LICENSE", "LIMIT", "LIQUID", "LIST", 
  "LIVING", "LOCAL", "LOCATE", "LOCKET", "LOGOUT", "LOYAL", "LUCKY", 
  "LUMBER", "LUNAR", "LUXURY", "MACHINE", "MAGIC", "MAGNET", "MAIL", 
  "MAIN", "MAJOR", "MAKER", "MANAGE", "MANUAL", "MARBLE", "MARKET", 
  "MASK", "MASTER", "MATCH", "MATRIX", "MAXIMUM", "MEAL", "MEASURE", 
  "MECHANIC", "MEDIUM", "MELODY", "MEMBER", "MENTAL", "MENTOR", "MENU", 
  "METAL", "METHOD", "METRIC", "MICRO", "MIDDLE", "MIGHTY", "MILLION", 
  "MINERAL", "MINIMUM", "MIRROR", "MISSION", "MIXER", "MOBILE", "MODULE", 
  "MOMENT", "MONITOR", "MONSTER", "MOTION", "MOTOR", "MOUNT", "MUSEUM", 
  "MUTATE", "MYSTERY", "NATIVE", "NATURAL", "NATURE", "NAVY", "NEAR", 
  "NEEDLE", "NEGATIVE", "NEON", "NEUTRAL", "NEWS", "NEXT", "NIGHTMARE", 
  "NOBLE", "NOISE", "NORMAL", "NORTH", "NOTICE", "NOVEL", "NUCLEAR", 
  "NUMBER", "OBJECT", "OBSERVE", "OCEAN", "OFFER", "ONLINE", "OPEN", 
  "OPERATE", "OPTION", "ORBIT", "ORDER", "ORGANIC", "ORIGIN", "OUTPUT", 
  "OWNER", "OXYGEN", "OZONE", "PACKET", "PAINT", "PALACE", "PANEL", 
  "PANIC", "PAPER", "PARADE", "PARALLEL", "PARENT", "PARTNER", "PASSAGE", 
  "PASSION", "PATIENT", "PATTERN", "PAYMENT", "PELICAN", "PENCIL", "PERFECT", 
  "PERIOD", "PERSON", "PHANTOM", "PHASE", "PHOTO", "PHYSICS", "PIANO", 
  "PICKLE", "PICTURE", "PILOT", "PINNACLE", "PIONEER", "PISTOL", "PIXEL", 
  "PLANET", "PLASTIC", "PLATFORM", "PLAYER", "PLEASE", "POCKET", "POEM", 
  "POETIC", "POINTER", "POISON", "POLICE", "POLICY", "POLISH", "POLITE", 
  "PORTAL", "PORTRAIT", "POSITION", "POSITIVE", "POSTER", "POTENTIAL", "POWDER", 
  "PRACTICE", "PRAYER", "PRECIOUS", "PREDICT", "PREMIUM", "PREPARE", "PRESENT", 
  "PRESERVE", "PRESS", "PREVIEW", "PRICE", "PRIDE", "PRIMARY", "PRIME", 
  "PRINCE", "PRINTER", "PRISON", "PRIVATE", "PRIZE", "PROBLEM", "PROCESS", 
  "PRODUCT", "PROFILE", "PROFIT", "PROGRAM", "PROJECT", "PROMISE", "PROMPT", 
  "PROOF", "PROPER", "PROTECT", "PROUD", "PUBLIC", "PULSE", "PUNCH", 
  "PUPIL", "PURE", "PURITY", "PURPLE", "PURPOSE", "PUZZLE", "QUALITY", 
  "QUANTUM", "QUARTER", "QUEEN", "QUERY", "QUEST", "QUESTION", "QUICK", 
  "QUIET", "QUOTA", "QUOTE", "RACING", "RADAR", "RADICAL", "RADIO", 
  "RADIUS", "RANDOM", "RANGER", "RAPID", "RARE", "RATING", "RATIO", 
  "RAZOR", "REACH", "REACTION", "READER", "READY", "REALITY", "REASON", 
  "REBEL", "RECALL", "RECEIPT", "RECENT", "RECIPE", "RECORD", "RECOVER", 
  "RECYCLE", "REDUCE", "REFINE", "REFLECT", "REFORM", "REFRESH", "REFUSE", 
  "REGION", "REGISTER", "REGRET", "REGULAR", "REJECT", "RELAX", "RELEASE", 
  "RELIEF", "RELOAD", "REMAIN", "REMARK", "REMIND", "REMOTE", "REPAIR", 
  "REPEAT", "REPORT", "RESCUE", "RESEARCH", "RESERVE", "RESET", "RESIGN", 
  "RESIST", "RESORT", "RESOURCE", "RESPECT", "RESTORE", "RESULT", "RETAIL",
  "RETIRE", "REVEAL", "REVERSE", "REWARD", "RHYTHM", "RIBBON", "RIDDLE", 
  "RIGID", "RISING", "RITUAL", "ROBOTIC", "ROCKET", "ROLLER", "ROMANCE", 
  "ROUGH", "ROUTE", "ROYAL", "RUBBER", "RULER", "RUMOR", "RUNNER", 
  "RUSTIC", "SACRED", "SAFETY", "SAILOR", "SAMPLE", "SANDAL", "SATIRE", 
  "SAVAGE", "SAVING", "SCALAR", "SCALED", "SCENE", "SCHEME", "SCHOOL", 
  "SCIENCE", "SCOOP", "SCOPE", "SCORCH", "SCORE", "SCOUT", "SCRAP", 
  "SCREEN", "SCRIBE", "SCROLL", "SEARCH", "SEASON", "SECOND", "SECRET", 
  "SECTOR", "SECURE", "SEEING", "SEGMENT", "SELECT", "SELLER", "SENSOR", 
  "SERENE", "SERIAL", "SERIES", "SETTLE", "SEVERE", "SHADOW", "SHAKY", 
  "SHARED", "SHARP", "SHIELD", "SHIFT", "SHINE", "SHIVER", "SHOCK", 
  "SHORE", "SHORT", "SHOULDER", "SHOVEL", "SHOWER", "SIGNAL", "SILENT", 
  "SILVER", "SIMILAR", "SIMPLE", "SINGLE", "SISTER", "SKETCH", "SKILL", 
  "SKULL", "SLEEPY", "SLIGHT", "SLOGAN", "SMOOTH", "SOCIAL", "SOFTLY", 
  "SOLAR", "SOLACE", "SOLID", "SOLVE", "SONAR", "SOURCE", "SPACE", 
  "SPARK", "SPEECH", "SPEED", "SPHERE", "SPIRIT", "SPLASH", "SPOKE", 
  "SPONSOR", "SPORT", "SPREAD", "SPRING", "SQUARE", "STABLE", "STACK", 
  "STAGE", "STAMP", "STATIC", "STATUS", "STEADY", "STEAM", "STEEL", 
  "STICKY", "STIFF", "STILL", "STING", "STOCK", "STONE", "STORE", 
  "STORM", "STORY", "STREAM", "STREET", "STRESS", "STRETCH", "STRICT", 
  "STRIKE", "STRING", "STRIPE", "STRONG", "STUDIO", "SUBMIT", "SUBTLE", 
  "SUDDEN", "SUFFER", "SUGAR", "SUMMIT", "SUMMON", "SUNSET", "SUPERB",
  // --- আরও নতুন শব্দ (Batch 8: Short & Meaningful) ---
  "SWIFT", "SWING", "SYMIT", "TABLE", "TACKLE", "TALENT", "TARGET", 
  "TASK", "TASTE", "TEAM", "TEAR", "TECH", "TEMPO", "TEND", 
  "TENT", "TERM", "TEST", "TEXT", "THANK", "THEFT", "THEME", 
  "THEORY", "THICK", "THIN", "THING", "THINK", "THIRD", "THORN", 
  "THREAT", "THUMB", "TICK", "TIDAL", "TIDY", "TIER", "TIGER", 
  "TIGHT", "TILE", "TILL", "TIME", "TINT", "TINY", "TIP", 
  "TIRE", "TITLE", "TOAST", "TOKEN", "TOLL", "TONE", "TOOL", 
  "TOPIC", "TORCH", "TOTAL", "TOUCH", "TOUGH", "TOUR", "TOWER", 
  "TOWN", "TRACE", "TRACK", "TRADE", "TRAIN", "TRAIT", "TRAP", 
  "TRAY", "TREAT", "TREND", "TRIAL", "TRIBE", "TRICK", "TRIM", 
  "TRIP", "TRUE", "TRUST", "TRUTH", "TUBE", "TUCK", "TUNE", 
  "TURN", "TWIN", "TWIST", "TYPE", "UNIT", "UNITE", "UNITY", 
  "UPSET", "URBAN", "URGE", "USAGE", "USER", "UTTER", "VAGUE", 
  "VALVE", "VAPOR", "VARY", "VAST", "VAULT", "VEIN", "VENT", 
  "VERB", "VERSE", "VEST", "VETO", "VIA", "VICE", "VIEW", 
  "VIGOR", "VILLA", "VINE", "VIRAL", "VITAL", "VOCAL", "VOID", 
  "VOLT", "VOTE", "VOWEL", "WAGE", "WAKE", "WALK", "WALL", 
  "WANT", "WARM", "WARN", "WASH", "WASP", "WATCH", "WAVE", 
  "WEAK", "WEAR", "WEAVE", "WEB", "WEDGE", "WEED", "WEEK", 
  "WEEP", "WELD", "WELL", "WEST", "WET", "WHALE", "WHEAT", 
  "WHEEL", "WHILE", "WHIP", "WHITE", "WHOLE", "WIDE", "WIDTH", 
  "WIFE", "WILD", "WILL", "WIND", "WINE", "WING", "WINK", "WIPE",
  // --- নতুন শব্দ: শুরু 'A' দিয়ে (Batch 9: Words starting with A) ---
  "ABANDON", "ABILITY", "ABOARD", "ABOVE", "ABROAD", "ABSENT", "ABSORB", 
  "ABSURD", "ACCENT", "ACCEPT", "ACCESS", "ACCORD", "ACCUSE", "ACHIEVE", 
  "ACIDIC", "ACQUIRE", "ACROSS", "ACTING", "ACTIVE", "ACTUAL", "ADAPT", 
  "ADDING", "ADDICT", "ADJOIN", "ADJUST", "ADMIRE", "ADMIT", "ADOPT", 
  "ADORE", "ADRIFT", "ADULT", "ADVENT", "ADVICE", "ADVISE", "AERIAL", 
  "AFFAIR", "AFFECT", "AFFIRM", "AFFORD", "AFLOAT", "AFRAID", "AFTER", 
  "AGAINST", "AGENCY", "AGENDA", "AGENT", "AGILE", "AGONY", "AGREE", 
  "AHEAD", "AIDING", "AILMENT", "AIRWAY", "ALARM", "ALBUM", "ALERT", 
  "ALIBI", "ALIEN", "ALIGN", "ALIKE", "ALIVE", "ALLEY", "ALLIED", 
  "ALLOW", "ALLOY", "ALMOST", "ALONE", "ALONG", "ALOUD", "ALPHA", 
  "ALPINE", "ALTAR", "ALTER", "ALWAYS", "AMAZED", "AMBER", "AMBIT", 
  "AMBLE", "AMEND", "AMINO", "AMISS", "AMITY", "AMONG", "AMOUNT", 
  "AMPLY", "AMUSE", "ANCHOR", "ANCIENT", "ANGEL", "ANGER", "ANGLE", 
  "ANGRY", "ANIMAL", "ANKLE", "ANNEX", "ANNOY", "ANNUAL", "ANSWER", 
  "ANTHEM", "ANTICS", "ANTIQUE", "ANVIL", "ANYHOW", "ANYONE", "ANYWAY", 
  "APART", "APATHY", "APEX", "APPEAL", "APPEAR", "APPEND", "APPLE", 
  "APPLY", "APPOINT", "APPROVE", "APRIL", "APRON", "ARCADE", "ARCHER", 
  "ARCHIVE", "ARCTIC", "ARDENT", "ARENA", "ARGUE", "ARISE", "ARMOR", 
  "AROUND", "AROUSE", "ARRAY", "ARRIVE", "ARROW", "ARSON", "ARTIST", 
  "ASCEND", "ASCENT", "ASHES", "ASIDE", "ASPECT", "ASPIRE", "ASSESS", 
  "ASSIGN", "ASSIST", "ASSUME", "ASSURE", "ASTRAY", "ASTRID", "ASYLUM", 
  "ATOMIC", "ATTACH", "ATTACK", "ATTAIN", "ATTEND", "ATTIRE", "ATTIC",
  // --- আরও নতুন শব্দ: শুরু 'A' দিয়ে (Batch 10) ---
  "ABACK", "ABATE", "ABBEY", "ABIDE", "ABLAZE", "ABLE", "ABODE", 
  "ABORT", "ABOUND", "ABRADE", "ABRUPT", "ABSTAIN", "ABSTRACT", "ABUSE", 
  "ABYSS", "ACACIA", "ACCEDE", "ACCLAIM", "ACCOST", "ACCRUE", "ACCURATE", 
  "ACETIC", "ACID", "ACME", "ACORN", "ACQUIT", "ACRE", "ACRID", 
  "ACROBAT", "ACRONYM", "ACROSTIC", "ACTOR", "ACTUATE", "ACUMEN", "ADAGE", 
  "ADAMANT", "ADDEND", "ADDER", "ADDLE", "ADDUCE", "ADEPT", "ADHERE", 
  "ADIEU", "ADIPOSE", "ADJACENT", "ADJUNCT", "ADJURE", "ADJUSTER", "ADMIRAL", 
  "ADMIX", "ADMONISH", "ADO", "ADONIS", "ADOPTIVE", "ADORN", "ADRENAL", 
  "ADROIT", "ADSORB", "ADULATION", "ADULTER", "ADUMBER", "ADVANCE", "ADVENTURE", 
  "ADVERB", "ADVERSE", "ADVERT", "ADVOCATE", "ADZE", "AEON", "AERATE", 
  "AESTHETE", "AFFABLE", "AFFECTED", "AFFIDAVIT", "AFFILIATE", "AFFINITY", "AFFIX", 
  "AFFLICT", "AFFLUENT", "AFFRONT", "AFIELD", "AFIRE", "AFOOT", "AFORE", 
  "AFRESH", "AFTERNOON", "AFTERWARD", "AGATE", "AGELESS", "AGGREGATE", "AGGRIEVE", 
  "AGHAST", "AGILE", "AGITATE", "AGLEAM", "AGLOW", "AGNOSTIC", "AGRARIAN", 
  "AGROUND", "AGUE", "AIDANCE", "AIGRETTE", "AILERON", "AIRILY", "AIRLINE", 
  "AIRPORT", "AIRSHIP", "AIRTIGHT", "AJAR", "AKIN", "ALABASTER", "ALACRITY", 
  "ALARMIST", "ALBEIT", "ALBINO", "ALBUMEN", "ALCHEMY", "ALCOHOL", "ALCOVE", 
  "ALDER", "ALEHOUSE", "ALERTON", "ALFALFA", "ALGAE", "ALGEBRA", "ALIAS", 
  "ALIMENT", "ALIMONY", "ALIQUOT", "ALKALI", "ALLAY", "ALLEGE", "ALLEGIANT", 
  "ALLEGORY", "ALLEGRO", "ALLERGEN", "ALLERGY", "ALLEVIATE", "ALLOT", "ALLOWANCE", 
  "ALLUDE", "ALLURE", "ALLUVIAL", "ALMANAC", "ALMIGHTY", "ALMOND", "ALMONER", // --- আরও নতুন শব্দ: শুরু 'A' দিয়ে (Batch 11) ---
  "ALOFT", "ALOHA", "ALPACA", "ALPHA", "ALREADY", "ALRIGHT", "ALSIKE", 
  "ALSO", "ALTER", "ALUMNA", "ALUMNI", "ALUMNAE", "ALUMNI", "ALWAYS", 
  "AMAIN", "AMALGAM", "AMASS", "AMATEUR", "AMATORY", "AMAZE", "AMAZON", 
  "AMBASSY", "AMBER", "AMBIENT", "AMBIT", "AMBLED", "AMBUSH", "AMELIOR", 
  "AMENITY", "AMETHYST", "AMIABLE", "AMICABLE", "AMIDST", "AMMONIA", "AMNESTY", 
  "AMOEBA", "AMOROUS", "AMORPH", "AMORTIZE", "AMOUNT", "AMPERE", "AMPHIB", 
  "AMPLIFY", "AMPLITUDE", "AMPOULE", "AMPUTATE", "AMULET", "AMUSE", "ANAGRAM", 
  "ANALOG", "ANALYST", "ANALYZE", "ANAPEST", "ANARCHY", "ANATHEM", "ANATOMY", 
  "ANCESTRY", "ANCHOR", "ANCHOVY", "ANCIENT", "ANCILLA", "ANDANTE", "ANECDOT", 
  "ANEMIA", "ANEMONE", "ANEW", "ANGELIC", "ANGINA", "ANGLER", "ANGULAR", 
  "ANHYDR", "ANILINE", "ANIMISM", "ANIMUS", "ANISETTE", "ANKLET", "ANNALS", 
  "ANNEAL", "ANNELID", "ANNOTATE", "ANNOUNCE", "ANNULAR", "ANNUL", "ANODE", 
  "ANODYNE", "ANOINT", "ANOMALY", "ANON", "ANOREXIA", "ANOTHER", "ANSWER", 
  "ANTACID", "ANTAGON", "ANTE", "ANTEATER", "ANTELOPE", "ANTENNA", "ANTERIOR", 
  "ANTHEM", "ANTHER", "ANTHILL", "ANTHOLOGY", "ANTHROPO", "ANTIBODY", "ANTIC", 
  "ANTIGEN", "ANTIMONY", "ANTIQUE", "ANTLER", "ANTONYM", "ANXIOUS", "ANYBODY", 
  "ANYHOW", "ANYONE", "ANYTHING", "ANYWAY", "AORTA", "APACE", "APART", 
  "APATHY", "APERIENT", "APERTURE", "APEX", "APHASIA", "APHID", "APHORISM", 
  "APIARY", "APIECE", "APISH", "APLOMB", "APOCALYP", "APOGEE", "APOLOGY", 
  "APOPLEXY", "APOSTLE", "APPALL", "APPARAT", "APPAREL", "APPEAL", "APPEAR", 
  "APPEASE", "APPELLAT", "APPEND", "APPENDIX", "APPETITE", "APPLAUD", "APPLIANCE",
  // --- নতুন শব্দ: শুরু 'B' দিয়ে (Batch 12) ---
  "BABBITT", "BABBLE", "BABOON", "BABY", "BACK", "BACKEND", "BACKUP", 
  "BACON", "BADGE", "BADLY", "BAFFLE", "BAGGAGE", "BAKERY", "BALANCE", 
  "BALLAD", "BALLOT", "BAMBOO", "BANANA", "BANDAGE", "BANDIT", "BANISH", 
  "BANKER", "BANNER", "BANQUET", "BANTER", "BARBARA", "BARBER", "BARELY", 
  "BARGAIN", "BARLEY", "BARREL", "BARRIER", "BARTER", "BASHFUL", "BASIC", 
  "BASIN", "BASKET", "BATCH", "BATTLE", "BEACON", "BEADLE", "BEAGLE", 
  "BEAMING", "BEANIE", "BEARER", "BEAST", "BEAUTY", "BEAVER", "BECOME", 
  "BEDROOM", "BEECH", "BEFORE", "BEGGAR", "BEGIN", "BEHALF", "BEHAVE", 
  "BEHIND", "BEHOLD", "BELIEF", "BELONG", "BELOVE", "BENCH", "BENDER", 
  "BENEFIT", "BENIGN", "BERRY", "BERTH", "BESIDE", "BESTOW", "BETRAY", 
  "BETTER", "BEVERAGE", "BEWARE", "BEYOND", "BIAS", "BIBLE", "BICEP", 
  "BICKER", "BICYCLE", "BIDDER", "BIGOT", "BILGE", "BILLBOARD", "BILLION", 
  "BINARY", "BINDER", "BINGE", "BINOCLE", "BIOLOGY", "BIPED", "BIRCH", 
  "BISHOP", "BISON", "BITTER", "BLACK", "BLADDER", "BLADE", "BLANK", 
  "BLAST", "BLAZE", "BLEACH", "BLEED", "BLEND", "BLESS", "BLIGHT", 
  "BLIND", "BLINK", "BLISS", "BLISTER", "BLOCK", "BLOND", "BLOOD", 
  "BLOOM", "BLOSSOM", "BLOTCH", "BLOUSE", "BLUNDER", "BLUNT", "BLURRY", 
  "BOARD", "BOAST", "BOATMAN", "BOBBIN", "BODILY", "BOILER", "BOLDLY", 
  "BOLSTER", "BOMBARD", "BONDAGE", "BONNET", "BONUS", "BOOMER", "BOOST", 
  "BORDER", "BORROW", "BOSOM", "BOTANY", "BOTTLE", "BOTTOM", "BOUNCE", 
  "BOUNTY", "BOURNE", "BOWLER", "BOXER", "BOYCOTT", "BRACE", "BRACKET",
  // --- নতুন শব্দ: শুরু 'C' দিয়ে (Batch 13) ---
  "CABINET", "CACKLE", "CACTUS", "CADENCE", "CAMERA", "CAMPUS", "CANAL", 
  "CANCEL", "CANCER", "CANDID", "CANDLE", "CANDOR", "CANINE", "CANVAS", 
  "CANYON", "CAPABLE", "CAPACITY", "CAPITAL", "CAPSULE", "CAPTAIN", "CAPTION", 
  "CAPTURE", "CARAVAN", "CARBON", "CARDIA", "CAREER", "CAREFUL", "CARGO", 
  "CARING", "CARNAGE", "CARNIVAL", "CARPET", "CARRIER", "CARROT", "CARTON", 
  "CASCADE", "CASSETTE", "CASTLE", "CATALOG", "CATALYST", "CATCHER", "CATEGORY", 
  "CATER", "CATTLE", "CAUSAL", "CAUTION", "CAVERN", "CEASE", "CELEST", 
  "CELLAR", "CEMENT", "CENSOR", "CENSUS", "CENTER", "CENTRAL", "CENTURY", 
  "CERAMIC", "CEREAL", "CERTAIN", "CHAKRA", "CHALLEN", "CHAMBER", "CHAMPION", 
  "CHANCE", "CHANGE", "CHANNEL", "CHAPTER", "CHARIOT", "CHARITY", "CHARM", 
  "CHARTER", "CHASSIS", "CHATTER", "CHEAP", "CHECKER", "CHEER", "CHEESE", 
  "CHEMICAL", "CHERRY", "CHESS", "CHICKEN", "CHIEF", "CHILD", "CHILLY", 
  "CHIMNEY", "CHOICE", "CHORUS", "CHROME", "CHRONIC", "CHUBBY", "CHUCKLE", 
  "CHURCH", "CIGAR", "CINEMA", "CIRCLE", "CIRCUIT", "CIRCUS", "CITIZEN", 
  "CITRUS", "CIVIC", "CIVIL", "CLAIM", "CLAMOR", "CLARITY", "CLASSIC", 
  "CLAUSE", "CLEANER", "CLEARLY", "CLERICAL", "CLEVER", "CLIENT", "CLIMATE", 
  "CLIMAX", "CLINIC", "CLOSET", "CLOTH", "CLOUD", "CLOVER", "CLUTCH", 
  "COAST", "COBALT", "COBRA", "COCONUT", "COFFEE", "COGNIT", "COHERENT", 
  "COHORT", "COINAGE", "COLLECT", "COLLEGE", "COLONY", "COLUMN", "COMBAT", 
  "COMBINE", "COMEDY", "COMFORT", "COMMAND", "COMMENT", "COMMIT", "COMMON", 
  "COMPACT", "COMPANY", "COMPARE", "COMPASS", "COMPETE", "COMPILE", "COMPLEX",
  // --- নতুন শব্দ: শুরু 'D' দিয়ে (Batch 14) ---
  "DAGGER", "DAILY", "DAIRY", "DAMAGE", "DANGER", "DANISH", "DAPPER", 
  "DARKLY", "DARLING", "DASHED", "DATABASE", "DATASET", "DAWN", "DAZZLE", 
  "DEADLY", "DEAFEN", "DEALER", "DEARLY", "DEBATE", "DEBIT", "DEBRIS", 
  "DEBUG", "DECADE", "DECENT", "DECIDE", "DECIMAL", "DECKER", "DECLARE", 
  "DECODE", "DECOR", "DECREE", "DEDUCE", "DEEDED", "DEEPEN", "DEEPLY", 
  "DEFEAT", "DEFECT", "DEFEND", "DEFINE", "DEFORM", "DEFRAY", "DEGREE", 
  "DELAY", "DELETE", "DELTA", "DEMAND", "DEMISE", "DENIAL", "DENOTE", 
  "DENSE", "DENTAL", "DEPART", "DEPEND", "DEPICT", "DEPLOY", "DEPORT", 
  "DEPOSIT", "DEPTH", "DEPUTY", "DERIVE", "DESCEND", "DESERT", "DESIGN", 
  "DESIRE", "DESKTOP", "DETACH", "DETAIL", "DETECT", "DETOUR", "DEVICE", 
  "DEVOTE", "DEVOUR", "DEVOUT", "DIAGRAM", "DIALECT", "DIALOG", "DIAMOND", 
  "DIARY", "DICTATE", "DIESEL", "DIFFER", "DIGEST", "DIGITAL", "DIGNITY", 
  "DILUTE", "DIMENSION", "DINNER", "DIPLOID", "DIRECT", "DIRTY", "DISABLE", 
  "DISCERN", "DISCO", "DISCORD", "DISCUSS", "DISDAIN", "DISEASE", "DISGUISE", 
  "DISHONOR", "DISLIKE", "DISMISS", "DISPLAY", "DISPOSE", "DISPUTE", "DISRUPT", 
  "DISTANCE", "DISTANT", "DISTORT", "DISTRICT", "DIVERSE", "DIVIDE", "DIVINE", 
  "DIVISION", "DOCILE", "DOCKET", "DOCTOR", "DOCUMENT", "DOMAIN", "DOMESTIC", 
  "DOMINANT", "DONATE", "DONKEY", "DOOMED", "DOORWAY", "DORMANT", "DOSAGE", 
  "DOUBLE", "DOUBT", "DOWNWARD", "DRAGON", "DRAINER", "DRAMA", "DRASTIC", 
  "DRAWER", "DREAD", "DREAMY", "DRENCH", "DRIFT", "DRIVE", "DROPLET", 
  "DROUGHT", "DROWSE", "DRYING", "DUALITY", "DUCTILE", "DUODEN", "DUPLEX", 
  "DURABLE", "DURING", "DYNAMIC", "DYNAMO", "DYNASTY",
  // --- আরও নতুন শব্দ: শুরু 'D' দিয়ে (Batch 15) ---
  "DABBLE", "DACTYL", "DAFFY", "DAINTY", "DALLY", "DAMASK", "DAMPER", 
  "DAPPLE", "DARING", "DARKEN", "DASHING", "DATING", "DAUBER", "DAUNT", 
  "DAWDLE", "DAZZLING", "DEACON", "DEALER", "DEARTH", "DEBASE", "DEBATE", 
  "DEBRIS", "DEBUNK", "DEBUT", "DECADES", "DECAMP", "DECANT", "DECEIT", 
  "DECENT", "DECIDE", "DECIMAL", "DECKLE", "DECLAIM", "DECLINE", "DECOCT", 
  "DECORUM", "DECOY", "DECREE", "DECRY", "DEDUCE", "DEEDED", "DEEFEN", 
  "DEFACE", "DEFAME", "DEFER", "DEFIANT", "DEFICIT", "DEFILE", "DEFINE", 
  "DEFLATE", "DEFLECT", "DEFORM", "DEFRAY", "DEFUSE", "DEFTLY", "DEGRADE", 
  "DEGREE", "DEIFY", "DEJECT", "DELAY", "DELECTA", "DELEGAT", "DELETE", 
  "DELFT", "DELIGHT", "DELIMIT", "DELIVER", "DELOUSE", "DELPHI", "DELUDE", 
  "DELUGE", "DELUXE", "DEMISE", "DEMURE", "DENIAL", "DENIER", "DENIM", 
  "DENOUNCE", "DENTAL", "DENTIST", "DENTURE", "DEPEND", "DEPICT", "DEPLORE", 
  "DEPLOY", "DEPORT", "DEPOSE", "DEPOSIT", "DEPOT", "DEPTHS", "DEPUTY", 
  "DERAIL", "DERIDE", "DERIVE", "DERMAL", "DESCANT", "DESCEND", "DESERT", 
  "DESERVE", "DESIGN", "DESIRE", "DESIST", "DESORB", "DESPAIR", "DESPITE", 
  "DESPOT", "DESTINY", "DETACH", "DETAIL", "DETAIN", "DETECT", "DETER", 
  "DETEST", "DETOUR", "DEUCE", "DEVAST", "DEVELOP", "DEVIATE", "DEVICE", 
  "DEVIL", "DEVISE", "DEVOID", "DEVOTE", "DEVOUR", "DEVOUT", "DEWCLAW", 
  "DEWDROP", "DEXTER", "DIADEM", "DIAGNOS", "DIAGRAM", "DIALECT", "DIALOG", 
  "DIAMOND", "DIAPER", "DIARY", "DICE", "DICTATE", "DICTION", "DIDACT", 
  "DIESEL", "DIETARY", "DIFFER", "DIFFUSE", "DIGEST", "DIGGER", "DIGITAL", 
  "DIGNIFY", "DIGRESS", "DILEMMA", "DILUTE", "DIMENSION", "DIMPLE", "DINNER",
  // --- নতুন শব্দ: শুরু 'R' দিয়ে (Batch 16) ---
  "RABBIT", "RACCOON", "RADAR", "RADIAL", "RADIANT", "RADICAL", "RADIUS", 
  "RAFFLE", "RAGGED", "RAILWAY", "RAINDROP", "RAISED", "RAMBLE", "RANDOM", 
  "RANGER", "RANKING", "RANSOM", "RAPIDLY", "RARELY", "RATIFY", "RATING", 
  "RATIO", "RATTLE", "RAVAGE", "RAZOR", "REACH", "REACT", "REACTION", 
  "READABLE", "READER", "READY", "REALITY", "REALIZE", "REALLY", "REALM", 
  "REASON", "REBATE", "REBEL", "RECALL", "RECEIPT", "RECEIVE", "RECENT", 
  "RECIPE", "RECKON", "RECLAIM", "RECORD", "RECOVER", "RECRUIT", "RECYCLE", 
  "REDUCE", "REDUX", "REFER", "REFILL", "REFINE", "REFLECT", "REFORM", 
  "REFRESH", "REFUND", "REFUSE", "REGARD", "REGIME", "REGION", "REGISTER", 
  "REGRET", "REGULAR", "REJECT", "RELATE", "RELAX", "RELEASE", "RELIEF", 
  "RELOAD", "REMAIN", "REMARK", "REMEDY", "REMIND", "REMOTE", "REMOVE", 
  "RENAME", "RENDER", "RENEW", "RENTAL", "REPAIR", "REPEAT", "REPLACE", 
  "REPLY", "REPORT", "RESCUE", "RESEARCH", "RESERVE", "RESET", "RESIDE", 
  "RESIGN", "RESIST", "RESIZE", "RESORT", "RESOURCE", "RESPECT", "RESPOND", 
  "RESTORE", "RESULT", "RESUME", "RETAIL", "RETAIN", "RETIRE", "RETORT", 
  "RETURN", "REVEAL", "REVENGE", "REVERSE", "REVERT", "REVIEW", "REVISE", 
  "REVIVE", "REWARD", "RHYTHM", "RIBBON", "RICHLY", "RIDDLE", "RIDGET", 
  "RIDING", "RIFLE", "RIGHTS", "RIGID", "RIGOR", "RINGLE", "RISING", 
  "RITUAL", "RIVAL", "RIVER", "ROADWAY", "ROAST", "ROBOTIC", "ROCKET", 
  "RODENT", "ROLLER", "ROMANCE", "ROOFING", "ROOSTER", "ROTARY", "ROUGH", 
  "ROUND", "ROUTER", "ROUTINE", "ROYAL", "RUBBER", "RUDDER", "RUGGED", 
  "RULER", "RUMOR", "RUNNER", "RURAL", "RUSTIC", "RUTHLESS",
  // --- নতুন শব্দ: শুরু 'E' দিয়ে (Batch 17) ---
  "EAGER", "EAGLE", "EARLY", "EARTH", "EASEL", "EASILY", "EASTER", 
  "EATING", "EBONY", "ECCENT", "ECHOES", "ECLIPSE", "ECOLOGY", "ECONOMY", 
  "EDIBLE", "EDITED", "EDITOR", "EFFECT", "EFFORT", "EGGMAN", "EITHER", 
  "EJECT", "ELAPSE", "ELASTIC", "ELBOW", "ELDER", "ELECT", "ELEGANT", 
  "ELEMENT", "ELEPHANT", "ELEVATE", "ELITE", "ELLIPSE", "ELUSIVE", "EMAIL", 
  "EMBARK", "EMBED", "EMBLEM", "EMBODY", "EMBRACE", "EMERGE", "EMOJI", 
  "EMOTION", "EMPIRE", "EMPLOY", "EMPTY", "ENABLE", "ENACT", "ENAMEL", 
  "ENCODE", "ENCORE", "ENDURE", "ENERGY", "ENFORCE", "ENGAGE", "ENGINE", 
  "ENJOY", "ENLARGE", "ENOUGH", "ENRICH", "ENROLL", "ENSURE", "ENTAIL", 
  "ENTER", "ENTIRE", "ENTITY", "ENTRY", "ENUMER", "ENVOY", "ENZYME", 
  "EPISODE", "EQUAL", "EQUATE", "EQUIP", "EQUITY", "ERASE", "ERODE", 
  "ERRAND", "ERROR", "ESCAPE", "ESCORT", "ESKIMO", "ESSAY", "ESTATE", 
  "ESTEEM", "ETHICS", "ETHNIC", "EULOGY", "EUREKA", "EVADE", "EVENT", 
  "EVERY", "EVICT", "EVIDENT", "EVOKE", "EVOLVE", "EXACT", "EXALT", 
  "EXAMINE", "EXCEED", "EXCEL", "EXCEPT", "EXCESS", "EXCITE", "EXCUSE", 
  "EXECUTE", "EXEMPT", "EXERT", "EXHALE", "EXHAUST", "EXHIBIT", "EXILE", 
  "EXIST", "EXITED", "EXOTIC", "EXPAND", "EXPECT", "EXPEND", "EXPERT", 
  "EXPIRE", "EXPLAIN", "EXPLODE", "EXPLOIT", "EXPLORE", "EXPORT", "EXPOSE", 
  "EXPRESS", "EXTEND", "EXTENT", "EXTERN", "EXTINCT", "EXTRACT", "EXTRA", 
  "EXTREME", "EYELET", "EYELID", "EYESORE", "EAGERNESS", "EARNEST", "EARTHLY",
  // --- F থেকে J পর্যন্ত (Batch 18) ---
  "FABRIC", "FACADE", "FACIAL", "FACTOR", "FACTORY", "FACULTY", "FAILED", "FAILURE", "FAIRLY", "FAITH", "FALLEN", "FAMILY", "FAMOUS", "FANTASY", "FARMER", "FASHION", "FASTEN", "FATAL", "FATHER", "FAUCET", "FAVOR", "FEARLESS", "FEATURE", "FEDERAL", "FEEDBACK", "FEELING", "FELLOW", "FEMALE", "FENDER", "FERMENT", "FERRY", "FERTILE", "FESTIVE", "FETCH", "FICTION", "FIELD", "FIERCE", "FIFTY", "FIGHTER", "FIGURE", "FILTER", "FINANCE", "FINDER", "FINISH", "FIREWALL", "FISCAL", "FLAVOR", "FLIGHT", "FLOATING", "FLOWER", "FLUENT", "FLUID", "FOCUS", "FOLDER", "FOLLOW", "FOOTER", "FORBID", "FORCE", "FORECAST", "FOREIGN", "FORGET", "FORMAL", "FORMAT", "FORMULA", "FORTUNE", "FORWARD", "FOSSIL", "FOUND", "FRACTION", "FRAGILE", "FRAME", "FREEZE", "FREIGHT", "FRESH", "FRICTION", "FRIEND", "FRIGHT", "FRONTIER", "FROZEN", "FRUGAL", "FRUIT", "FUELING", "FULFILL", "FUNCTION", "FUNDING", "FUNNY", "FURIOUS", "FURNACE", "FUTURE", "GADGET", "GALAXY", "GALLERY", "GAMING", "GARAGE", "GARDEN", "GARLIC", "GATHER", "GAUGE", "GENDER", "GENERAL", "GENERIC", "GENETIC", "GENIUS", "GENTLE", "GENUINE", "GEOLOGY", "GESTURE", "GEYSER", "GHETTO", "GHOST", "GIANT", "GIFTED", "GIGGLE", "GINGER", "GIRAFFE", "GLACIER", "GLAMOR", "GLANCE", "GLASSY", "GLOBAL", "GLOOMY", "GLORIA", "GLOSSY", "GLOVE", "GLOWING", "GOALIE", "GOLDEN", "GOSPEL", "GOSSIP", "GOVERN", "GRACE", "GRADE", "GRADUAL", "GRAFT", "GRAMMAR", "GRAND", "GRANITE", "GRAPHIC", "GRASP", "GRASSY", "GRATIS", "GRAVITY", "GREEDY", "GREET", "GRID", "GRIEF", "GRIP", "GROSS", "GROUND", "GROUP", "GROWTH", "GUARD", "GUESS", "GUEST", "GUIDE", "GUITAR", "GUTTER", "HABIT", "HACKER", "HALTED", "HAMMER", "HANDLE", "HAPPEN", "HARBOR", "HARDLY", "HARVEST", "HAZARD", "HEADER", "HEALTH", "HEARING", "HEART", "HEATER", "HEAVEN", "HEIGHT", "HELPER", "HERITAGE", "HEROIC", "HIDDEN", "HIGHLY", "HIKING", "HISTORY", "HOLDER", "HOLLOW", "HONEST", "HONOR", "HORIZON", "HORROR", "HOSPIT", "HOSTEL", "HOSTING", "HOTEL", "HOURLY", "HOUSE", "HUMAN", "HUMBLE", "HUNTER", "HYBRID", "HYDRATE", "HYGIENE", "HYPHEN", "ICONIC", "IDEAL", "IDENT", "IDIOM", "IGNORE", "ILLNESS", "IMAGE", "IMPACT", "IMPORT", "IMPOSE", "IMPROVE", "INCH", "INCIDE", "INCLUDE", "INCOME", "INDEBT", "INDEX", "INDICAT", "INDOOR", "INDUCE", "INFANT", "INFECT", "INFER", "INFINIT", "INFLOW", "INFORM", "INGRESS", "INHERIT", "INITIAL", "INJECT", "INJURE", "INLAND", "INLINE", "INNER", "INPUT", "INQUIRY", "INSANE", "INSECT", "INSIDE", "INSIGHT", "INSTALL", "INSTANT", "INSURE", "INTACT", "INTAKE", "INTEGER", "INTEND", "INTENSE", "INTENT", "INTERN", "INVADE", "INVENT", "INVERT", "INVEST", "INVITE", "INVOICE", "INVOLVE", "IONIC", "ISLAND", "ISOLATE", "ISSUED", "ITALIC", "JACKET", "JAGGED", "JANITOR", "JARGON", "JASMINE", "JAVELIN", "JEALOUS", "JELLY", "JERSEY", "JESTER", "JEWEL", "JINGLE", "JOBLESS", "JOINER", "JOINT", "JORDAN", "JOURNAL", "JOURNEY", "JOYFUL", "JUDGE", "JUDICIAL", "JUICE", "JUMBLE", "JUMPER", "JUNGLE", "JUNIOR", "JUPITER", "JUSTICE", "JUSTIFY", // --- K থেকে O পর্যন্ত (Batch 19) ---
  "KANSAS", "KARATE", "KEEPER", "KERNEL", "KETTLE", "KEYBOARD", "KICKER", "KIDNAP", "KIDNEY", "KILLED", "KILLER", "KINDLY", "KINETIC", "KINGDOM", "KITCHEN", "KITTEN", "KNIGHT", "KNITTED", "KNOCK", "KNOTTY", "KNOWING", "LABELED", "LABOR", "LADDER", "LADY", "LAGOON", "LAMBDA", "LANDING", "LANTERN", "LAPTOP", "LARGER", "LARYNX", "LATELY", "LATENT", "LATEST", "LATTICE", "LAUNCH", "LAWFUL", "LAWYER", "LAYOUT", "LEADER", "LEAGUE", "LEARNED", "LEASE", "LEATHER", "LEGACY", "LEGAL", "LEGEND", "LEMON", "LENDER", "LENGTH", "LENSES", "LESSON", "LETTER", "LEVEL", "LIABLE", "LIBERAL", "LIBRARY", "LICENSE", "LIFTER", "LIGHTLY", "LIKELY", "LIMITED", "LINEAR", "LINEUP", "LINKED", "LIQUID", "LISTING", "LITTLE", "LIVELY", "LOADER", "LOANER", "LOCALLY", "LOCATE", "LOCKET", "LOGGING", "LOGICAL", "LONELY", "LOOKUP", "LOOPER", "LOOSEN", "LOTTERY", "LOUNGE", "LOVING", "LOYALTY", "LUCENT", "LUCKILY", "LUMBAR", "LUMEN", "LUMINO", "LUMPY", "LUNAR", "LUNCHEON", "LUXURY", "LYRICS", "MACHINE", "MAGNET", "MAIDEN", "MAILER", "MAINLY", "MAINTAIN", "MAJESTY", "MAKEUP", "MALICE", "MAMMAL", "MANAGE", "MANDATE", "MANNER", "MANUAL", "MAPLE", "MARGIN", "MARINE", "MARKET", "MASKED", "MASTER", "MATRIX", "MAXIMUM", "MEANING", "MEASURE", "MECHANIC", "MEDAL", "MEDIA", "MEDICAL", "MEDIUM", "MELODY", "MEMBER", "MEMORY", "MENTAL", "MENTOR", "MERELY", "MERGER", "MERIT", "MESSAGE", "METAL", "METHOD", "METRIC", "METRO", "MICRO", "MIDDLE", "MIDWAY", "MIGHTY", "MIGRANT", "MILEAGE", "MILITARY", "MILLION", "MINERAL", "MINIMUM", "MINING", "MINION", "MINOR", "MIRROR", "MISERY", "MISSILE", "MISSION", "MISTAKE", "MIXTURE", "MOBILE", "MODAL", "MODERN", "MODIFY", "MODULE", "MOMENT", "MONARCH", "MONITOR", "MONKEY", "MONTHLY", "MORNING", "MORTAL", "MOTIVE", "MOUNTAIN", "MOUNTED", "MOVING", "MUSEUM", "MUSICAL", "MUTUAL", "MYSTERY", "NAMELY", "NARROW", "NATIVE", "NATURAL", "NATURE", "NAUSEA", "NEARLY", "NEBULA", "NECK", "NEEDLE", "NEGATE", "NEPHEW", "NERVOUS", "NETWORK", "NEUTRAL", "NEWLY", "NICKEL", "NIECE", "NIGHTLY", "NIMBLE", "NITRO", "NOBLE", "NODAL", "NOISE", "NOMADIC", "NOMINAL", "NORMAL", "NOTABLE", "NOTIFY", "NOTION", "NOVEL", "NOZZLE", "NUCLEAR", "NUGGET", "NUMBER", "NUMERIC", "NURSERY", "OBJECT", "OBLIGE", "OBSERVE", "OBTAIN", "OBVIOUS", "OCCUPY", "OCCUR", "OCEANIC", "OCTAVE", "OCULAR", "ODDITY", "OFFENSE", "OFFERED", "OFFICE", "OFFLINE", "OFFSET", "OLIVE", "OMEGA", "OMISSION", "ONION", "ONLINE", "OPAQUE", "OPENER", "OPERATE", "OPINION", "OPTICAL", "OPTIMAL", "OPTION", "ORACLE", "ORANGE", "ORBITAL", "ORCHARD", "ORDERED", "ORDINAL", "ORGANIC", "ORIGIN", "ORNAMENT", "ORPHAN", "OUTCOME", "OUTDOOR", "OUTLET", "OUTLINE", "OUTPUT", "OUTSIDE", "OVERALL", "OVERLAP", "OVERTIME", "OWNER",
  // --- S থেকে Z পর্যন্ত (Batch 20) ---
  "SACRED", "SADDLE", "SAFELY", "SAILING", "SALARY", "SAMPLE", "SANDAL", "SATIRE", "SAVAGE", "SAVING", "SCALAR", "SCALED", "SCARCE", "SCHEMA", "SCHOOL", "SCIENCE", "SCREEN", "SCRIPT", "SEARCH", "SEASON", "SECOND", "SECRET", "SECTOR", "SECURE", "SELECT", "SELLER", "SENSOR", "SERENE", "SERIAL", "SERIES", "SERVER", "SETTLE", "SEVERE", "SHADOW", "SHAKY", "SHARED", "SHARP", "SHIELD", "SHIFT", "SHINE", "SHIVER", "SHOCK", "SHORE", "SHORT", "SIGNAL", "SILENT", "SILVER", "SIMPLE", "SINGLE", "SISTER", "SKETCH", "SKILL", "SLIGHT", "SLOGAN", "SMOOTH", "SOCIAL", "SOFTLY", "SOLAR", "SOLID", "SOLVE", "SOURCE", "SPACE", "SPARK", "SPEECH", "SPEED", "SPHERE", "SPIRIT", "SPLASH", "SPORT", "SPREAD", "SPRING", "SQUARE", "STABLE", "STACK", "STAGE", "STATIC", "STATUS", "STEADY", "STEEL", "STICKY", "STILL", "STOCK", "STONE", "STORE", "STORM", "STORY", "STREAM", "STREET", "STRESS", "STRICT", "STRIKE", "STRING", "STRIPE", "STRONG", "STUDIO", "SUBMIT", "SUBTLE", "SUDDEN", "SUFFER", "SUGAR", "SUMMIT", "SUNDAY", "SUNSET", "SUPERB", "SUPPLY", "SURELY", "SURFACE", "SURVEY", "SWITCH", "SYMBOL", "SYSTEM", "TABLET", "TACKLE", "TAGGED", "TALENT", "TARGET", "TARIFF", "TASSEL", "TATTOO", "TAUGHT", "TEACHER", "TEAMER", "TECHNO", "TELLER", "TEMPLE", "TENANT", "TENDER", "TENNIS", "TENURE", "TERMIN", "TERROR", "TESTER", "TEXTUAL", "THEORY", "THERMAL", "THESIS", "THINGS", "THIRTY", "THREAT", "THRILL", "THROUGH", "TICKET", "TIDAL", "TIGER", "TIMELY", "TIMING", "TISSUE", "TITLED", "TOKEN", "TONGUE", "TOPIC", "TORQUE", "TOTAL", "TOUCH", "TOWARD", "TOWER", "TRACKER", "TRADER", "TRADIT", "TRAFFIC", "TRAGED", "TRAILER", "TRAINER", "TRANSIT", "TREASURE", "TREATY", "TRENDY", "TRIBAL", "TRICKY", "TRIPLE", "TROPHY", "TROPIC", "TRUSTY", "TUNNEL", "TURKEY", "TWELVE", "TWENTY", "TYPING", "ULTRA", "UNABLE", "UNCLE", "UNDER", "UNEQUAL", "UNIFY", "UNIQUE", "UNITARY", "UNITED", "UNITY", "UNIVER", "UNKNOWN", "UNLESS", "UPDATE", "UPHOLD", "UPLIFT", "UPLOAD", "UPPER", "UPWARD", "URGENT", "USABLE", "USEFUL", "USER", "UTMOST", "VACANT", "VACUUM", "VAGUELY", "VALLEY", "VALUED", "VALVE", "Vanish", "VAPOR", "VARIED", "VASSAL", "VECTOR", "VEGGIE", "VEHICLE", "VELVET", "VENDOR", "VENOM", "VENTURE", "VERBAL", "VERIFY", "VERSION", "VESSEL", "VIABLE", "VICTIM", "VICTOR", "VIDEO", "VIEWER", "VIGOR", "VIKING", "VILLAGE", "VIOLIN", "VIRTUAL", "VISIBLE", "VISION", "VISUAL", "VITAL", "VOCAL", "VOICE", "VOLUME", "VORTEX", "VOTING", "VOWEL", "VOYAGE", "WALLET", "WALNUT", "WANDER", "WANTED", "WARMER", "WASHER", "WASTED", "WATCH", "WATERY", "WEALTH", "WEAPON", "WEATHER", "WEAVER", "WEEKLY", "WEIGHT", "WEIRD", "WELCOME", "WELFARE", "WESTERN", "WHEEL", "WHENCE", "WIDELY", "WIDGET", "WILDLY", "WINDOW", "WINNER", "WINTER", "WIRING", "WISDOM", "WIZARD", "WOLF", "WONDER", "WOODEN", "WORKER", "WORLD", "WORTHY", "WRITER", "WRONG", "XENON", "XEROX", "XYLEM", "YACHT", "YARD", "YEARLY", "YELLOW", "YIELD", "YOUNGER", "YOUTH", "ZEBRA", "ZENITH", "ZERO", "ZIGZAG", "ZINC", "ZIPPER", "ZODIAC", "ZOMBIE", "ZONING",
"ONE", "TWO", "THREE", "FOUR", "FIVE", "SIX", "SEVEN", "EIGHT", "NINE", "TEN", "ELEVEN", "TWELVE", "THIRTEEN", "FOURTEEN", "FIFTEEN", "SIXTEEN", "SEVENTEEN", "EIGHTEEN", "NINETEEN", "TWENTY", "NEED", "ON", "SOON", "UP", "TOO", "EASY", "NOTHING", "PAN", "CAR", "CUT", "CUP", "TO", "READ", "REST", "NEXT", "SEA", "LEVEL", "YEAR", "TEXT", "TEXI", "ZOO", "ZOOM", "CITY", "DOG", "FOX", "FOG", "BRID", "SHIP", "SOLID", "SHOP", "MAN", "WAR", "CAT", "TAG", "BAG", "BUG", "BAD", "SON", "DROP", "DOT", "DUTY", "FREE", "FEE", "FOR", "OF", "CAN", "COME", "GO", "AFTER", "UPON", "WARM", "COLD", "UNITY"];
const SIZE = 10;

const createGrid = () =>
  Array.from({ length: SIZE * SIZE }, () => ({
    letter: "",
    owner: null,
    isWord: false,
    counted: false,
  }));

export default function App() {
  const [grid, setGrid] = useState(createGrid());
  const [activeCell, setActiveCell] = useState(null);
  const [player, setPlayer] = useState(1);
  const [score, setScore] = useState({ 1: 0, 2: 0 });

  /* ---------------- CLICK HANDLERS ---------------- */

  const onCellClick = (i) => {
    if (grid[i].letter) return;
    setActiveCell(i);
  };

  const onLetterClick = (letter) => {
    if (activeCell === null) return;

    setGrid((prev) => {
      const copy = [...prev];
      copy[activeCell] = {
        ...copy[activeCell],
        letter,
        owner: player, // প্রাথমিক মালিক
      };
      return copy;
    });

    setActiveCell(null);
    setPlayer((p) => (p === 1 ? 2 : 1));
  };

  /* ---------------- WORD CHECK ---------------- */

  // এখানে currentPlayer প্যারামিটার যোগ করা হয়েছে
  const checkLine = (indexes, currentPlayer) => {
    let word = "";
    let cells = [];

    indexes.forEach((i) => {
      if (grid[i].letter) {
        word += grid[i].letter;
        cells.push(i);
      } else {
        validate(word, cells, currentPlayer);
        word = "";
        cells = [];
      }
    });

    validate(word, cells, currentPlayer);
  };

  const validate = (word, cells, currentPlayer) => {
    if (word.length < 2) return;
    if (!DICTIONARY.includes(word)) return;
    
    // যদি শব্দের সব অক্ষর আগে থেকেই 'counted' থাকে তবে স্কিপ করবে
    if (cells.every((i) => grid[i].counted)) return;

    setGrid((prev) => {
      const copy = [...prev];
      cells.forEach((i) => {
        copy[i] = {
          ...copy[i],
          isWord: true,
          counted: true,
          owner: currentPlayer, // যে প্লেয়ার শব্দ বানালো, পুরো শব্দের মালিক সে
        };
      });
      return copy;
    });

    setScore((prev) => ({
      ...prev,
      [currentPlayer]: prev[currentPlayer] + cells.length,
    }));
  };

  useEffect(() => {
    // যেহেতু onLetterClick এ প্লেয়ার চেঞ্জ হয়ে যায়, 
    // তাই শেষ চাল দেওয়া প্লেয়ারকে বের করতে হবে।
    const lastPlayer = player === 1 ? 2 : 1;

    // Row Check
    for (let r = 0; r < SIZE; r++) {
      checkLine(
        Array.from({ length: SIZE }, (_, c) => r * SIZE + c),
        lastPlayer
      );
    }

    // Column Check
    for (let c = 0; c < SIZE; c++) {
      checkLine(
        Array.from({ length: SIZE }, (_, r) => r * SIZE + c),
        lastPlayer
      );
    }
  }, [grid]);

  /* ---------------- GAME END ---------------- */

  useEffect(() => {
    if (grid.every((c) => c.letter !== "")) {
      const winner = score[1] > score[2] ? "Player 1 Wins 🟢" : "Player 2 Wins 🔵";
      alert(score[1] === score[2] ? "It's a Draw! 🤝" : winner);
    }
  }, [grid]);

  return (
    <div className="min-h-screen bg-gray-900 p-6">
      <h1 className="text-3xl font-bold text-center pb-4 text-white font-serif border-b border-green-600">
        Word Game
      </h1>

      <div className="flex justify-around text-white my-8 max-w-4xl m-auto">
        <div className={`text-2xl font-bold font-mono py-2 px-6 rounded-2xl transition-all ${player === 1 ? "bg-green-600 scale-110 shadow-lg shadow-green-900" : "bg-black opacity-50"}`}>
          🟢 P1: {score[1]}
        </div>
        <div className={`text-2xl font-bold font-mono py-2 px-6 rounded-2xl transition-all ${player === 2 ? "bg-blue-600 scale-110 shadow-lg shadow-blue-900" : "bg-black opacity-50"}`}>
          🔵 P2: {score[2]}
        </div>
      </div>

      {/* LETTERS */}
      <div className="max-w-3xl m-auto">
        <div className="flex flex-wrap justify-center gap-2 mb-8">
          {LETTERS.map((l) => (
            <Word key={l} value={l} onClick={() => onLetterClick(l)} />
          ))}
        </div>
      </div>

      {/* GRID */}
      <div className="max-w-2xl m-auto bg-black p-4 rounded-2xl shadow-2xl border border-gray-700">
        <div className="grid grid-cols-10 gap-1 sm:gap-2 justify-center">
          {grid.map((cell, i) => (
            <WordBox
              key={i}
              cell={cell}
              active={activeCell === i}
              onClick={() => onCellClick(i)}
              currentPlayer={player}
            />
          ))}
        </div>
      </div>
    </div>
  );
}